### ISSUE TITLE
Customization using configuration files

### ISSUE THREAD

**Issue by burntcarrot** [burntcarrot/pairpad#29]
Users should be able to use a configuration file to customize the editor.

Here is an example:

```toml
theme = "onedark"

[editor]
word-wrap=false
```
